server:
  port:
    8093

spring:
  datasource:
    url: jdbc:postgresql://dpg-ct890i9opnds73bupb60-a.oregon-postgres.render.com/iot_data_xcm6
    username: iot_data_xcm6_user
    password: a2awAwiNY4xqDeIu0Zqqrka7LYhm4PMs
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect