server:
  port:
    8093

spring:
  datasource:
    url: jdbc:postgresql://dpg-crgf2kbv2p9s73abj2kg-a.oregon-postgres.render.com:5432/iotdata_o0hp
    username: k1melo
    password: wDtA1koV3yZuqi7PzIGAKKIO9Bab9NQB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect