server:
  port:
    8093

spring:
  datasource:
    url: jdbc:postgresql://dpg-csfc8nrtq21c738mc5j0-a.oregon-postgres.render.com/iot_data
    username: iot_data_user
    password: m1a5qEDsngnsmHka3yiW8vtHyPtH48ig
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect